require 'net/http'
  def parse_data(url)
    uri = URI(url)
    req = Net::HTTP::Get.new(uri)
    req['Token'] = "c0f9912bdcb90b81c198c2ed64cb0d782a52447d"
    res = Net::HTTP.start(uri.hostname, uri.port) {|http|http.request(req)}
    parsed_data = JSON.parse(res.body)
  end

  def populate_categories
    parsed_data = parse_data("http://wger.de/api/v2/exercisecategory/")
    parsed_data["results"].each do |category|
      new_cat = Category.create
      new_cat.update(id: category["id"], name: category["name"])
    end
  end

  def populate_muscles
    parsed_data = parse_data("http://wger.de/api/v2/muscle/")
    parsed_data["results"].each do |muscle|
      new_muscle = Muscle.create
      new_muscle.update(id: muscle["id"], name: muscle["name"])
    end
  end

  def populate_exercise
    for i in 1..27
      parsed_data = parse_data("http://wger.de/api/v2/exercise/?page=#{i}")

      english_exercises = parsed_data["results"].select!{|exercise| exercise["language"] == 2 && !exercise["muscles"].blank?}

      english_exercises.each do |exercise|
        new_exercise = Exercise.create
        new_exercise.update(name: exercise["name"], description: exercise["description"], muscle_ids: exercise["muscles"], category_id: exercise["category"])
      end
    end
  end


populate_categories
populate_muscles
populate_exercise


Muscle.find(1).update(category_name: "Arms")
Muscle.find(2).update(category_name: "Shoulders")
Muscle.find(3).update(category_name: "Abs")
Muscle.find(4).update(category_name: "Chest")
Muscle.find(5).update(category_name: "Arms")
Muscle.find(6).update(category_name: "Abs")
Muscle.find(7).update(category_name: "Calves")
Muscle.find(8).update(category_name: "Legs")
Muscle.find(9).update(category_name: "Arms")
Muscle.find(10).update(category_name: "Legs")
Muscle.find(11).update(category_name: "Legs")
Muscle.find(12).update(category_name: "Back")
Muscle.find(13).update(category_name: "Arms")
Muscle.find(14).update(category_name: "Abs")
Muscle.find(15).update(category_name: "Calves")

Muscle.find(1).update(image_url: 'muscles/bicepsbrachii.jpeg')
Muscle.find(2).update(image_url: 'muscles/anteriordeltoid.jpeg')
Muscle.find(3).update(image_url: 'muscles/Serratusanterior.jpeg')
Muscle.find(4).update(image_url: 'muscles/Pectoralismajor.jpeg')
Muscle.find(5).update(image_url: 'muscles/Tricepsbrachii.jpeg')
Muscle.find(6).update(image_url: 'muscles/Rectusabdominis.jpeg')
Muscle.find(10).update(image_url: 'muscles/Quadricepsfemoris.jpeg')
Muscle.find(11).update(image_url: 'muscles/Bicepsfemoris.jpeg')
Muscle.find(13).update(image_url: 'muscles/Brachialis.jpeg')
Muscle.find(7).update(image_url: 'muscles/Gastrocnemius.jpeg')
Muscle.find(8).update(image_url: 'muscles/Gluteusmaximus.jpeg')
Muscle.find(9).update(image_url: 'muscles/Trapezius.jpeg')
Muscle.find(12).update(image_url: 'muscles/Latissimusdorsi.jpeg')
Muscle.find(14).update(image_url: 'muscles/Obliquusexternusabdominis.jpeg')
Muscle.find(15).update(image_url: 'muscles/Soleus.jpeg')



Category.find(10).update(image_url: 'abs.jpeg')
Category.find(8).update(image_url: 'arms.jpeg')
Category.find(12).update(image_url: 'back.jpeg')
Category.find(14).update(image_url: 'calves.jpeg')
Category.find(11).update(image_url: 'chest.jpeg')
Category.find(9).update(image_url: 'legs.jpeg')
Category.find(13).update(image_url: 'shoulders.jpeg')


Exercise.find(1).update(image_url: "https://www.youtube.com/embed/S5kOK3bxfro")
Exercise.find(2).update(image_url: "https://www.youtube.com/embed/JjeVfsYbYmU")
Exercise.find(3).update(image_url: "https://www.youtube.com/embed/JjeVfsYbYmU")
Exercise.find(4).update(image_url: "https://www.youtube.com/embed/JjeVfsYbYmU")
Exercise.find(5).update(image_url: "https://www.youtube.com/embed/S5kOK3bxfro")
Exercise.find(6).update(image_url: "https://www.youtube.com/embed/O-d6HC9gLcw")
Exercise.find(7).update(image_url: "https://www.youtube.com/embed/rT7DgCr-3pg")
Exercise.find(8).update(image_url: "https://www.youtube.com/embed/EdtaJRBqwes")
Exercise.find(9).update(image_url: "https://www.youtube.com/embed/Zp26q4BY5HE")
Exercise.find(10).update(image_url: "https://www.youtube.com/embed/0_9sJd9P8M0")
Exercise.find(11).update(image_url: "https://www.youtube.com/embed/1oed-UmAxFs")
Exercise.find(12).update(image_url: "https://www.youtube.com/embed/LVqdtjlzJWQ")
Exercise.find(13).update(image_url: "https://www.youtube.com/embed/ORUVgqJLHEU")
Exercise.find(14).update(image_url: "https://www.youtube.com/embed/Xyma7Bkvds0")
Exercise.find(15).update(image_url: "https://www.youtube.com/embed/Xyma7Bkvds0")
Exercise.find(16).update(image_url: "https://www.youtube.com/embed/SHsUIZiNdeY")
Exercise.find(17).update(image_url: "https://www.youtube.com/embed/nEF0bv2FW94")
Exercise.find(18).update(image_url: "https://www.youtube.com/embed/_5tJG8iNpkA")
Exercise.find(19).update(image_url: "https://www.youtube.com/embed/6TSP1TRMUzs")
Exercise.find(20).update(image_url: "https://www.youtube.com/embed/6TSP1TRMUzs")
Exercise.find(21).update(image_url: "https://www.youtube.com/embed/6TSP1TRMUzs")
Exercise.find(22).update(image_url: "https://www.youtube.com/embed/in7PaeYlhrM")
Exercise.find(23).update(image_url: "https://www.youtube.com/embed/in7PaeYlhrM")
Exercise.find(24).update(image_url: "https://www.youtube.com/embed/in7PaeYlhrM")
Exercise.find(25).update(image_url: "https://www.youtube.com/embed/in7PaeYlhrM")
Exercise.find(26).update(image_url: "https://www.youtube.com/embed/in7PaeYlhrM")
Exercise.find(27).update(image_url: "https://www.youtube.com/embed/qYlIKzZYrOI")
Exercise.find(28).update(image_url: "https://www.youtube.com/embed/4Hl1WAGKjMc")
Exercise.find(29).update(image_url: "https://www.youtube.com/embed/4Hl1WAGKjMc")
Exercise.find(30).update(image_url: "https://www.youtube.com/embed/wiFNA3sqjCA")
Exercise.find(31).update(image_url: "https://www.youtube.com/embed/wiFNA3sqjCA")
Exercise.find(32).update(image_url: "https://www.youtube.com/embed/sa1k_vNTPWo")
Exercise.find(33).update(image_url: "https://www.youtube.com/embed/Txp-M94xLTo")
Exercise.find(34).update(image_url: "https://www.youtube.com/embed/Y7AvQH8MCHg")
Exercise.find(35).update(image_url: "https://www.youtube.com/embed/Qr7dstCeYtw")
Exercise.find(36).update(image_url: "https://www.youtube.com/embed/Qr7dstCeYtw")
Exercise.find(37).update(image_url: "https://www.youtube.com/embed/taI4XduLpTk")
Exercise.find(38).update(image_url: "https://www.youtube.com/embed/zw49Dw45eCc")
Exercise.find(39).update(image_url: "https://www.youtube.com/embed/zw49Dw45eCc")
Exercise.find(40).update(image_url: "https://www.youtube.com/embed/zw49Dw45eCc")
Exercise.find(41).update(image_url: "https://www.youtube.com/embed/zw49Dw45eCc")
Exercise.find(42).update(image_url: "https://www.youtube.com/embed/hXdB-qariQ4")
Exercise.find(43).update(image_url: "https://www.youtube.com/embed/-M4-G8p8fmc")
Exercise.find(44).update(image_url: "https://www.youtube.com/embed/BJrBYoxR-jQ")
Exercise.find(45).update(image_url: "https://www.youtube.com/embed/bd_A0kDAyK4")
Exercise.find(46).update(image_url: "https://www.youtube.com/embed/bd_A0kDAyK4")
Exercise.find(47).update(image_url: "https://www.youtube.com/embed/QM4eWrcLVZ4")
Exercise.find(48).update(image_url: "https://www.youtube.com/embed/nEF0bv2FW94&t=10s")
Exercise.find(49).update(image_url: "https://www.youtube.com/embed/ecRF8ERf2q4")
Exercise.find(50).update(image_url: "https://www.youtube.com/embed/tpLnfSQJ0gg")
Exercise.find(51).update(image_url: "https://www.youtube.com/embed/Xyd_fa5zoEU")
Exercise.find(52).update(image_url: "https://www.youtube.com/embed/Xyd_fa5zoEU")
Exercise.find(53).update(image_url: "https://www.youtube.com/embed/Xyd_fa5zoEU")
Exercise.find(54).update(image_url: "https://www.youtube.com/embed/RyJbvWAh6ec")
Exercise.find(55).update(image_url: "https://www.youtube.com/embed/LfyQBUKR8SE")
Exercise.find(56).update(image_url: "https://www.youtube.com/embed/LfyQBUKR8SE")
Exercise.find(57).update(image_url: "https://www.youtube.com/embed/LfyQBUKR8SE")
Exercise.find(58).update(image_url: "https://www.youtube.com/embed/LfyQBUKR8SE")
Exercise.find(59).update(image_url: "https://www.youtube.com/embed/iN7e-KEkidw")
Exercise.find(60).update(image_url: "https://www.youtube.com/embed/sM6XUdt1rm4")
Exercise.find(61).update(image_url: "https://www.youtube.com/embed/sM6XUdt1rm4")
Exercise.find(62).update(image_url: "https://www.youtube.com/embed/78fBPxkCfao")
Exercise.find(63).update(image_url: "https://www.youtube.com/embed/y1r9toPQNkM")
Exercise.find(64).update(image_url: "https://www.youtube.com/embed/y1r9toPQNkM")
Exercise.find(65).update(image_url: "https://www.youtube.com/embed/y1r9toPQNkM")
Exercise.find(66).update(image_url: "https://www.youtube.com/embed/y1r9toPQNkM")
Exercise.find(67).update(image_url: "https://www.youtube.com/embed/y1r9toPQNkM")
Exercise.find(68).update(image_url: "https://www.youtube.com/embed/y1r9toPQNkM")
Exercise.find(69).update(image_url: "https://www.youtube.com/embed/y1r9toPQNkM")
Exercise.find(70).update(image_url: "https://www.youtube.com/embed/y1r9toPQNkM")
Exercise.find(71).update(image_url: "https://www.youtube.com/embed/y1r9toPQNkM")
Exercise.find(72).update(image_url: "https://www.youtube.com/embed/y1r9toPQNkM")
Exercise.find(73).update(image_url: "https://www.youtube.com/embed/y1r9toPQNkM")
Exercise.find(74).update(image_url: "https://www.youtube.com/embed/rep-qVOkqgk")
Exercise.find(75).update(image_url: "https://www.youtube.com/embed/Fkzk_RqlYig")
Exercise.find(76).update(image_url: "https://www.youtube.com/embed/DNx0PYv7_L8")
Exercise.find(77).update(image_url: "https://www.youtube.com/embed/eozdVDA78K0")
Exercise.find(78).update(image_url: "https://www.youtube.com/embed/eozdVDA78K0")
Exercise.find(79).update(image_url: "https://www.youtube.com/embed/JImgCWzCHwI")
Exercise.find(80).update(image_url: "https://www.youtube.com/embed/JImgCWzCHwI")
Exercise.find(81).update(image_url: "https://www.youtube.com/embed/JImgCWzCHwI")
Exercise.find(82).update(image_url: "https://www.youtube.com/embed/-t7fuZ0KhDA")
Exercise.find(83).update(image_url: "https://www.youtube.com/embed/VfBOBhwXbro")
Exercise.find(84).update(image_url: "https://www.youtube.com/embed/5aje8NexO60")
Exercise.find(85).update(image_url: "https://www.youtube.com/embed/8bbE64NuDTU")
Exercise.find(86).update(image_url: "https://www.youtube.com/embed/zC3nLlEvin4")
Exercise.find(87).update(image_url: "https://www.youtube.com/embed/hdng3Nm1x_E")
Exercise.find(88).update(image_url: "https://www.youtube.com/embed/5ihi0QG-rCM")
Exercise.find(89).update(image_url: "https://www.youtube.com/embed/KPR1ATD9wjQ")
Exercise.find(90).update(image_url: "https://www.youtube.com/embed/KPR1ATD9wjQ")
Exercise.find(91).update(image_url: "https://www.youtube.com/embed/_5tJG8iNpkA&t=10s")
Exercise.find(92).update(image_url: "https://www.youtube.com/embed/fDP6O_aJpDg")
Exercise.find(93).update(image_url: "https://www.youtube.com/embed/fDP6O_aJpDg")
Exercise.find(94).update(image_url: "https://www.youtube.com/embed/fDP6O_aJpDg")
Exercise.find(95).update(image_url: "https://www.youtube.com/embed/n-H5EpKcP60")
Exercise.find(96).update(image_url: "https://www.youtube.com/embed/CgbmrF-DRSE")
Exercise.find(97).update(image_url: "https://www.youtube.com/embed/SrqOu55lrYU")
Exercise.find(98).update(image_url: "https://www.youtube.com/embed/SrqOu55lrYU")
Exercise.find(99).update(image_url: "https://www.youtube.com/embed/SrqOu55lrYU")
Exercise.find(100).update(image_url: "https://www.youtube.com/embed/gaEDgmhbT0s")
Exercise.find(101).update(image_url: "https://www.youtube.com/embed/Me9bHFAxnCs")
Exercise.find(102).update(image_url: "https://www.youtube.com/embed/VxrSMH5vVWY")
Exercise.find(103).update(image_url: "https://www.youtube.com/embed/LD1xSc7oRRk")
Exercise.find(104).update(image_url: "https://www.youtube.com/embed/LD1xSc7oRRk")
Exercise.find(105).update(image_url: "https://www.youtube.com/embed/LD1xSc7oRRk")
Exercise.find(106).update(image_url: "https://www.youtube.com/embed/YSxHifyI6s8")
Exercise.find(107).update(image_url: "https://www.youtube.com/embed/b_LEX4n9lOs")
Exercise.find(108).update(image_url: "https://www.youtube.com/embed/b_LEX4n9lOs")
Exercise.find(109).update(image_url: "https://www.youtube.com/embed/b_LEX4n9lOs")
Exercise.find(110).update(image_url: "https://www.youtube.com/embed/CAwf7n6Luuc")
Exercise.find(111).update(image_url: "https://www.youtube.com/embed/CAwf7n6Luuc")
Exercise.find(112).update(image_url: "https://www.youtube.com/embed/ELOCsoDSmrg")
Exercise.find(113).update(image_url: "https://www.youtube.com/embed/IZxyjW7MPJQ")
Exercise.find(114).update(image_url: "https://www.youtube.com/embed/IZxyjW7MPJQ")
Exercise.find(115).update(image_url: "https://www.youtube.com/embed/IZxyjW7MPJQ")
Exercise.find(116).update(image_url: "https://www.youtube.com/embed/JB2oyawG9KI&t=3s")
Exercise.find(117).update(image_url: "https://www.youtube.com/embed/JB2oyawG9KI&t=3s")
Exercise.find(118).update(image_url: "https://www.youtube.com/embed/ME_VyhsiBd8")
Exercise.find(119).update(image_url: "https://www.youtube.com/embed/ME_VyhsiBd8")
Exercise.find(120).update(image_url: "https://www.youtube.com/embed/ME_VyhsiBd8")
Exercise.find(121).update(image_url: "https://www.youtube.com/embed/G1BlS-MHacw")
Exercise.find(122).update(image_url: "https://www.youtube.com/embed/G1BlS-MHacw")
Exercise.find(123).update(image_url: "https://www.youtube.com/embed/nBc_2Jyp3tM")
Exercise.find(124).update(image_url: "https://www.youtube.com/embed/IUZJoSP66HI")
Exercise.find(125).update(image_url: "https://www.youtube.com/embed/X59_4RrU_aA")
Exercise.find(126).update(image_url: "https://www.youtube.com/embed/2yjwXTZQDDI")
Exercise.find(127).update(image_url: "https://www.youtube.com/embed/JWZkK0ydn-o")
Exercise.find(128).update(image_url: "https://www.youtube.com/embed/JWZkK0ydn-o")
Exercise.find(129).update(image_url: "https://www.youtube.com/embed/AV5PmZJIrrw")
Exercise.find(130).update(image_url: "https://www.youtube.com/embed/AV5PmZJIrrw")
Exercise.find(131).update(image_url: "https://www.youtube.com/embed/Ow58yHEl_Ls")
Exercise.find(132).update(image_url: "https://www.youtube.com/embed/dVM-rN5cd4E")
Exercise.find(133).update(image_url: "https://www.youtube.com/embed/XYMVy8CmtFU")
Exercise.find(134).update(image_url: "https://www.youtube.com/embed/h4nkoayPFWw")
Exercise.find(135).update(image_url: "https://www.youtube.com/embed/IODxDxX7oi4")
Exercise.find(136).update(image_url: "https://www.youtube.com/embed/IODxDxX7oi4")
Exercise.find(137).update(image_url: "https://www.youtube.com/embed/PZlLHZ4Venw")
Exercise.find(138).update(image_url: "https://www.youtube.com/embed/pSHjTRCQxIw")
Exercise.find(139).update(image_url: "https://www.youtube.com/embed/pSHjTRCQxIw")
Exercise.find(140).update(image_url: "https://www.youtube.com/embed/KjGvwQl8tis")
Exercise.find(141).update(image_url: "https://www.youtube.com/embed/fIWP-FRFNU0")
Exercise.find(142).update(image_url: "https://www.youtube.com/embed/DzW1TnJChD0")
Exercise.find(143).update(image_url: "https://www.youtube.com/embed/DzW1TnJChD0")
Exercise.find(144).update(image_url: "https://www.youtube.com/embed/DzW1TnJChD0")
Exercise.find(145).update(image_url: "https://www.youtube.com/embed/DzW1TnJChD0")
Exercise.find(146).update(image_url: "https://www.youtube.com/embed/ep30avTSMB0")
Exercise.find(147).update(image_url: "https://www.youtube.com/embed/IODxDxX7oi4&t=13s")
Exercise.find(148).update(image_url: "https://www.youtube.com/embed/RyJbvWAh6ec&t=13s")
Exercise.find(149).update(image_url: "https://www.youtube.com/embed/didEQUuieRQ")
Exercise.find(150).update(image_url: "https://www.youtube.com/embed/hyv14e2QDq0")
Exercise.find(151).update(image_url: "https://www.youtube.com/embed/WZkhTEMddG8")
Exercise.find(152).update(image_url: "https://www.youtube.com/embed/g5WypZGRzgI")
Exercise.find(153).update(image_url: "https://www.youtube.com/embed/ATE2JtZCZh8")
Exercise.find(154).update(image_url: "https://www.youtube.com/embed/w2hGNM4l5so")
Exercise.find(155).update(image_url: "https://www.youtube.com/embed/w2hGNM4l5so")
Exercise.find(156).update(image_url: "https://www.youtube.com/embed/w2hGNM4l5so")
Exercise.find(157).update(image_url: "https://www.youtube.com/embed/wkD8rjkodUI")
Exercise.find(158).update(image_url: "https://www.youtube.com/embed/YbX7Wd8jQ-Q")
Exercise.find(159).update(image_url: "https://www.youtube.com/embed/GZbfZ033f74")
Exercise.find(160).update(image_url: "https://www.youtube.com/embed/GZbfZ033f74")
Exercise.find(161).update(image_url: "https://www.youtube.com/embed/GZbfZ033f74")
Exercise.find(162).update(image_url: "https://www.youtube.com/embed/GZbfZ033f74")
Exercise.find(163).update(image_url: "https://www.youtube.com/embed/qEwKCR5JCog")
Exercise.find(164).update(image_url: "https://www.youtube.com/embed/qEwKCR5JCog")
Exercise.find(165).update(image_url: "https://www.youtube.com/embed/qEwKCR5JCog")
Exercise.find(166).update(image_url: "https://www.youtube.com/embed/cJRVVxmytaM")
Exercise.find(167).update(image_url: "https://www.youtube.com/embed/cJRVVxmytaM")
Exercise.find(168).update(image_url: "https://www.youtube.com/embed/K2VljzCC16g")
Exercise.find(169).update(image_url: "https://www.youtube.com/embed/K2VljzCC16g")
Exercise.find(170).update(image_url: "https://www.youtube.com/embed/K2VljzCC16g")
Exercise.find(171).update(image_url: "https://www.youtube.com/embed/K2VljzCC16g")
Exercise.find(172).update(image_url: "https://www.youtube.com/embed/K2VljzCC16g")
Exercise.find(173).update(image_url: "https://www.youtube.com/embed/K2VljzCC16g")
Exercise.find(174).update(image_url: "https://www.youtube.com/embed/1fbU_MkV7NE")
Exercise.find(175).update(image_url: "https://www.youtube.com/embed/1fbU_MkV7NE")
Exercise.find(176).update(image_url: "https://www.youtube.com/embed/HAiyYtntcmA")
Exercise.find(177).update(image_url: "https://www.youtube.com/embed/HAiyYtntcmA")
Exercise.find(178).update(image_url: "https://www.youtube.com/embed/HAiyYtntcmA")
Exercise.find(179).update(image_url: "https://www.youtube.com/embed/HAiyYtntcmA")
Exercise.find(180).update(image_url: "https://www.youtube.com/embed/HAiyYtntcmA")
Exercise.find(181).update(image_url: "https://www.youtube.com/embed/HAiyYtntcmA")
Exercise.find(182).update(image_url: "https://www.youtube.com/embed/nEQQle9-0NA")
Exercise.find(183).update(image_url: "https://www.youtube.com/embed/nEQQle9-0NA")
Exercise.find(184).update(image_url: "https://www.youtube.com/embed/nEQQle9-0NA")
Exercise.find(185).update(image_url: "https://www.youtube.com/embed/nEQQle9-0NA")
Exercise.find(186).update(image_url: "https://www.youtube.com/embed/nEQQle9-0NA")
Exercise.find(187).update(image_url: "https://www.youtube.com/embed/nEQQle9-0NA")
Exercise.find(188).update(image_url: "https://www.youtube.com/embed/nEQQle9-0NA")
Exercise.find(189).update(image_url: "https://www.youtube.com/embed/nEQQle9-0NA")
Exercise.find(190).update(image_url: "https://www.youtube.com/embed/nEQQle9-0NA")
Exercise.find(191).update(image_url: "https://www.youtube.com/embed/nEQQle9-0NA")
Exercise.find(192).update(image_url: "https://www.youtube.com/embed/nEQQle9-0NA")
Exercise.find(193).update(image_url: "https://www.youtube.com/embed/nEQQle9-0NA")
Exercise.find(194).update(image_url: "https://www.youtube.com/embed/nEQQle9-0NA")
Exercise.find(195).update(image_url: "https://www.youtube.com/embed/nEQQle9-0NA")
Exercise.find(196).update(image_url: "https://www.youtube.com/embed/nEQQle9-0NA")
Exercise.find(197).update(image_url: "https://www.youtube.com/embed/d2s5pCQKBRU")
Exercise.find(198).update(image_url: "https://www.youtube.com/embed/d2s5pCQKBRU")
Exercise.find(199).update(image_url: "https://www.youtube.com/embed/d2s5pCQKBRU")
Exercise.find(200).update(image_url: "https://www.youtube.com/embed/d2s5pCQKBRU")
Exercise.find(201).update(image_url: "https://www.youtube.com/embed/d2s5pCQKBRU")
Exercise.find(202).update(image_url: "https://www.youtube.com/embed/d2s5pCQKBRU")
Exercise.find(203).update(image_url: "https://www.youtube.com/embed/d2s5pCQKBRU")
Exercise.find(204).update(image_url: "https://www.youtube.com/embed/d2s5pCQKBRU")
Exercise.find(205).update(image_url: "https://www.youtube.com/embed/d2s5pCQKBRU")
Exercise.find(206).update(image_url: "https://www.youtube.com/embed/d2s5pCQKBRU")
Exercise.find(207).update(image_url: "https://www.youtube.com/embed/d2s5pCQKBRU")
Exercise.find(208).update(image_url: "https://www.youtube.com/embed/d2s5pCQKBRU")
Exercise.find(209).update(image_url: "https://www.youtube.com/embed/9nbO_uTbo9o")
Exercise.find(210).update(image_url: "https://www.youtube.com/embed/9nbO_uTbo9o")
Exercise.find(211).update(image_url: "https://www.youtube.com/embed/acp77RhVzMM")
Exercise.find(212).update(image_url: "https://www.youtube.com/embed/acp77RhVzMM")
Exercise.find(213).update(image_url: "https://www.youtube.com/embed/acp77RhVzMM")
Exercise.find(214).update(image_url: "https://www.youtube.com/embed/acp77RhVzMM")
Exercise.find(215).update(image_url: "https://www.youtube.com/embed/acp77RhVzMM")
Exercise.find(216).update(image_url: "https://www.youtube.com/embed/acp77RhVzMM")
Exercise.find(217).update(image_url: "https://www.youtube.com/embed/acp77RhVzMM")
Exercise.find(218).update(image_url: "https://www.youtube.com/embed/y-wV4Venusw")
Exercise.find(219).update(image_url: "https://www.youtube.com/embed/y-wV4Venusw")
Exercise.find(220).update(image_url: "https://www.youtube.com/embed/y-wV4Venusw")
Exercise.find(221).update(image_url: "https://www.youtube.com/embed/y-wV4Venusw")
Exercise.find(222).update(image_url: "https://www.youtube.com/embed/y-wV4Venusw")
Exercise.find(223).update(image_url: "https://www.youtube.com/embed/y-wV4Venusw")


def update_exercise_description
  Exercise.all.each do |exercise|
    e =  exercise.description
    e =  e.gsub("</p>","")
    e =  e.gsub("<p>","")
    e =  e.gsub("</li>","")
    e =  e.gsub("<li>","")
    e =  e.gsub("<em>","")
    e =  e.gsub("</em>","")
    e =  e.gsub("<ol>","")
    e =  e.gsub("</ol>","")
    e =  e.gsub("</ul>","")
    e =  e.gsub("<ul>","")
    e =  e.gsub("\n", " ")

    exercise.update(description: e)
  end
end


update_exercise_description
















#
